# Generated by Django 4.0.3 on 2022-08-08 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sub_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkinModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(blank=True, upload_to='images')),
                ('url', models.CharField(blank=True, max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='image_classification',
        ),
    ]
